<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">

<head>
    <link rel="stylesheet" href="<?php echo $this->css?>" type="text/css">
    <script src="<?php echo $this->playerhtml5_js?>" type="text/javascript"></script>
    <script src="<?php echo $this->jquery?>" type="text/javascript"></script>

    <script src="<?php echo $this->jquery_i18n?>" type="text/javascript"></script>
    <script src="/locale/general-translation-table" type="text/javascript"></script>
    <link href='https://fonts.googleapis.com/css?family=Roboto:400,100,300,700' rel='stylesheet' type='text/css'>
    <script type="text/javascript">
        $.i18n.setDictionary(general_dict);

        var MAX_MOBILE_SCREEN_WIDTH = 760;

        var Html5Player = function() {
            var id_element=getRandomIdPlayer(3000);
            this.mobileDetect = this.mobileDetect();
            this.playerMode = "<?php echo $this->playerMode ?>";
            this.settings = {
                'elementId': id_element,    // ne pas toucher
                'autoplay': false,          // ou true (fonctionne que sur quelques navigateurs)
                'forceHTTPS': true,         // ou true si le flux est en SSL (attention au port d'écoute, habituellement 8000)
                'replacePort':false,        // false pour désactivé ou '8000' comme port de départ habituelle, oblige à indiquer replacePortTo.
                'replacePortTo':''          // soit '' pour utilisation du port par par default du navigateur (80/http, 443/https) ou '8443' pour forcer le port du flux.
              };

            if (this.playerMode == "manual") {
                this.settings.url = <?php echo $this->streamURL ?>;
                this.settings.codec = "<?php echo $this->codec ?>";
            } else if (this.playerMode == "file") {
                this.settings.url = <?php echo $this->streamURL ?>;
                this.settings.codec = "<?php echo $this->codec ?>";
            } else if (this.playerMode == "auto") {
                this.availableMobileStreamQueue = <?php echo $this->availableMobileStreams?>;
                this.availableDesktopStreamQueue = <?php echo $this->availableDesktopStreams?>;
                var stream = this.getNextAvailableStream();
                this.settings.url = stream["url"];
                this.settings.codec = stream["codec"];
            }

            // Create the Muses player object
            playerhtml5_insert(this.settings);
            playerhtml5_audio = document.getElementById(id_element);
            if(playerhtml5_audio.played==true) togglePlayStopButton();
            
            // Configure player title
            var player_title = <?php echo $this->player_title?>;
            if (player_title === null) {
                $(".airtime_header").hide();
                $(".airtime_player").css('height', '150px');
            } else {
                $("p.station_name").html(player_title);
            }

            attachStreamMetadataToPlayer();

            // detects events in HTML5 mode
            
        };


    </script>

    <style type="text/css">
        /*
        We have to have the default Muses skin displayed on the page or else
        the player will not work. Setting the display to none and hidden does
        not work. It has to be "visible" on the page. As a hacky work around we
        set the height and width to 1px so users will not see it.
        */
        #html5player_skin{width:0; height:0; overflow: hidden;}
    </style>

</head>

<body>

<div id="player" <?php if ($this->player_style == "basic") echo "style='display:block;'"; else echo "style='display:none'"; ?>>
    <div class="airtime_player">

        <div class="airtime_header">
            <p class="station_name">fff</p>
        </div>

        <div class="airtime_box">

            <div class="airtime_button">
                <span id="play_button" class="play_button" onclick="html5Player.play()"></span>
                <span id="stop_button" class="stop_button hide_button" onclick="html5Player.stop()"></span>
            </div>
            <p class="now_playing"></p>

        </div>

        <div style="clear:both"></div>

        <div class="airtime_schedule">
            <p class="airtime_next"><?php echo _("Next") ?></p>
            <ul class="schedule_list">
                <li></li>
            </ul>
        </div>
        <a class="airtime_pro" target="_blank" href="<?php echo PRODUCT_SITE_URL; ?>"><?php printf(_('Powered by %s'), PRODUCT_NAME); ?></a>

    </div>
</div>

<div id="premium_player" <?php if ($this->player_style == "premium") echo "style='display:block;'"; else echo "style='display:none'"; ?>>
    <div class="bottom_bar">
        <div class="play cont_btn"></div>

        <div class="on_air">
            <p class="now_playing"></p>
        </div>
    </div>

</div>

<div id="html5player_skin">
    <script type="text/javascript">
        var html5Player = new Html5Player();
    </script>
</div>

</body>
</html>
